### ISSUE TITLE
Hello, I have a code issue regarding the use of the CopyTo method

### ISSUE THREAD

**Issue by SuitedRioter** [BandoWare/GameplayTags#1]
Is there a problem with using CopyTo in GameplayTagContainer.cs? For example, in line 210, should your Clone method be written in this way: `m_Indices.CopyTo(clone.m_Indices);  ` Copy your own index to clone's index?

**Comment by felipemcoliveira** [comment]
It seems it’s not correct. I’m traveling, and I’ll fix it next week when I return. Thanks for opening the issue!

**Comment by felipemcoliveira** [comment]
@SuitedRioter I thought I had fixed the bug, but now I have actually resolved it!
