### ISSUE TITLE
Some Info wrong

### ISSUE THREAD

**Issue by MaiKuraki** [BandoWare/GameplayTags#4]
1. The name of the asmdef does not match the name of the namespace (BandoWare.GameplayTag.Editor.asmdef, BandoWare.GameplayTag.Tests.asmdef)
<img width="657" alt="O6nh6Vygkn" src="https://github.com/user-attachments/assets/4940eb6c-efb2-45b4-adc2-a205f338de59">

<img width="585" alt="y2WdizZuMK" src="https://github.com/user-attachments/assets/b29c940e-879f-4f17-8579-d2975a1094dd">

</br>
2. A runtime assembly is referencing the UnityEditor namespace.（GameplayTagContainerDebugView.cs）
<img width="713" alt="rHGIfCDwwG" src="https://github.com/user-attachments/assets/e11943ee-4d9d-409f-8166-80e5bc4074a6">

</br>
</br>
</br>
3. class GameplayTagUtility should be public, the method Validate used in the Tests

4. also class GameplayTagContainerPropertyDrawer is in the **BandoWare.GameplayAbilities.Editor** namespace

**Comment by felipemcoliveira** [comment]
Everything is already fixed in the [development](https://github.com/BandoWare/GameplayTags/tree/development) branch. Thanks for your contribution!
