### ISSUE TITLE
How to use source generator

### ISSUE THREAD

**Issue by JimSuo** [BandoWare/GameplayTags#6]
I Added a new element to AssembltInfo.cs. It does not automatically generate code. How should I execute the generator script? tks

**Comment by felipemcoliveira** [comment]
It's not necessary to run it; it's part of the compilation pipeline. It won't actually generate any files but will emit the code directly to the generator.

You can test it by registering a tag like this:
```csharp
[assembly: GameplayTag("A.B.C")]
```

Now, within the same assembly where you registered the tag, try using:
```csharp
AllGameplayTags.A.B.C.Get()
```

Make sure to include `BandoWare.GameplayTags` in your usings. Also check if

**Comment by JimSuo** [comment]
Thanks for your answer. I found the problem that I couldn't use static classes to access tags. The problem is not that the corresponding code is not generated, but that it cannot be accessed in the main assembly. I can't access it in assemblies other than the GameplayTags assembly.
And I also found that after I encapsulated my script into an .asmdef and configured BandoWare.GameplayTags's `[assembly: InternalsVisibleTo("GameplayFramework")]`.
I still couldn't access the static Tag type from the outside.

And I found that the .g.cs file where the AllGameplayTags class is located, which I cannot access in the IDE, is not the same as the .g.cs file that I can access in GameplayTags.
Unable to find definition：
![image](https://github.com/user-attachments/assets/725b82c0-0e75-4f79-9882-83dd73a0a5c0)
Jump to define:
![image](https://github.com/user-attachments/assets/f9892826-920f-48b7-ae61-f0f22480b858)
Definitions can be found：
![image](https://github.com/user-attachments/assets/1741de19-d18e-49e1-8e52-85a1cf1f53fb)
Jump to define:
![image](https://github.com/user-attachments/assets/eb26899c-3816-41c7-a969-eb15b58e48ea)

Looking forward to your answer，tks!!!

**Comment by JimSuo** [comment]
I found the solution. This was my own mistake. I shouldn't have created my own GameplayTag in AssemableInfo.cs under the Runtime folder of GameplayTags. I should have created it in my own module. After the modification, I can successfully access it! Thank you for your answer. This is a very good project. Thank you!

**Comment by felipemcoliveira** [comment]
Awesome! Glad you figured it out.
